#ifndef P43_HOST_STUB_APP_CONFIG_H
#define P43_HOST_STUB_APP_CONFIG_H

#define APP_TASK_IMU_PERIOD_US                  1000UL
#define APP_TASK_BAROMETER_PERIOD_US            5000UL
#define APP_TASK_LIDAR_PERIOD_US                1000UL
#define APP_TASK_NRF_PERIOD_US                  5000UL
#define APP_TASK_FULL_ESKF_CORRECTION_PERIOD_US 5000UL
#define APP_TASK_FULL_ESKF_COVARIANCE_PERIOD_US 40000UL
#define APP_TASK_SYSMON_PERIOD_US               100000UL

#define APP_TASK_IMU_BUDGET_US                  950UL
#define APP_TASK_BAROMETER_BUDGET_US            5000UL
#define APP_TASK_LIDAR_BUDGET_US                400UL
#define APP_TASK_NRF_BUDGET_US                  1000UL
#define APP_TASK_FULL_ESKF_CORRECTION_BUDGET_US 2500UL
#define APP_TASK_FULL_ESKF_COVARIANCE_BUDGET_US 650UL
#define APP_TASK_SYSMON_BUDGET_US               1000UL

#define APP_P34_IMU_GUARD_US                    40UL
#define APP_P34_ESKF_SLOT_RESERVE_US            610UL
#define APP_P34_BARO_SLOT_RESERVE_US            320UL
#define APP_P34_LIDAR_SLOT_RESERVE_US           360UL
#define APP_P34_NRF_SLOT_RESERVE_US             80UL
#define APP_P34_SYSMON_SLOT_RESERVE_US          450UL

#endif
